name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libcmocka-dev valgrind
    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON
    - name: Build
      run: cmake --build build
    - name: Test
      run: |
        cd build
        ctest --output-on-failure
    - name: Memory leak check
      run: |
        cd build
        ctest -T memcheck
    - name: Generate coverage
      if: success()
      run: |
        cd build
        gcov ../src/*.c
        bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

